apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-yktp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0043-tenant/tkrw-pr712-0075-0043-app/devfile-sample-yktp@sha256:274332ef613c8c9ab4ebf6fd2573553f95c76d4f2335b4fb1fb3e8e2dd3aedce
        name: my-nodejs
        resources: {}
status: {}
